### ISSUE TITLE
Rewrite Script system to follow javax.script API

### ISSUE THREAD

**Issue by hawkw** [MeteorCode/Pathway#3]

**Comment by ArcticLight** [comment]
I think at this point we probably want to have our system be a *client* of the Javax.script API, rather than an implementor of it. We're targeting one scripting language at the moment. If we feel we want to, later, I suppose we can expose the whole framework with an api such as this, but for now, I'd recommend iceboxing/closing this issue

**Comment by hawkw** [comment]
Seems legit.
